title: Zachary Hughes
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a computer science major from Grove City College, minoring in Data Science, Mathematics, and Game Design. Here is a small collection of the projects I've worked on.
  <br><br>
  Future assignments and projects will be updated on an as-created basis, but past projects may have been created locally or through a different management platform (such as Unity's proprietary service), which explains some of the shotgun uploads for my older work. 
  <br><br>
  <a href="https://www.linkedin.com/in/zachary-hughes-49055516b/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
